# run_full_validation.ps1 — Generate complete _validation/ tree for all AAPF samples
#
# For each of the 19 AAPF sample acquisitions, this script produces three
# verification outputs in samples/_validation/ :
#
#   <category>-<os>-<state>.esentutl.txt    — Windows native esentutl /mh
#   <category>-<os>-<state>.poneglyph.txt   — Universal-patched libesedb (via Poneglyph)
#   <category>-<os>-<state>.zeroed.json     — Fully-zeroed page distribution
#
# These outputs back the AAPF Matrix (Table 5), the integrity-loss numbers
# (Table 6), and the zeroed-page distribution (Table 7 in §4.4 of the paper).

[CmdletBinding()]
param(
    [switch]$Clean   # delete _validation/ before regenerating
)

$ErrorActionPreference = 'Continue'

$Root = Split-Path -Parent $PSScriptRoot
$SamplesDir = Join-Path $Root 'samples'
$ValDir = Join-Path $SamplesDir '_validation'
$Poneglyph = Join-Path $Root 'poneglyph\poneglyph.exe'
$ZeroScan = Join-Path $Root 'tools\scan_zeroed_pages.ps1'

if (-not (Test-Path $Poneglyph)) {
    throw "poneglyph.exe not found at $Poneglyph"
}

if ($Clean -and (Test-Path $ValDir)) {
    Write-Host "Removing existing $ValDir ..." -ForegroundColor Yellow
    Remove-Item -Recurse -Force $ValDir
}
if (-not (Test-Path $ValDir)) {
    New-Item -ItemType Directory -Path $ValDir | Out-Null
}

# Catalog of all expected samples
$Samples = @(
    # category, os, state, filename
    @('identity', '2019', 'clean',   'ntds.dit'),
    @('identity', '2019', 'crashed', 'ntds.dit'),
    @('identity', '2019', 'locked',  'ntds.dit'),
    @('identity', '2025', 'clean',   'ntds.dit'),
    @('identity', '2025', 'crashed', 'ntds.dit'),
    @('identity', '2025', 'locked',  'ntds.dit'),

    @('health',   '2019', 'clean',   'DataStore.edb'),
    @('health',   '2019', 'crashed', 'DataStore.edb'),
    @('health',   '2019', 'locked',  'DataStore.edb'),
    @('health',   '2025', 'clean',   'DataStore.edb'),
    @('health',   '2025', 'crashed', 'DataStore.edb'),
    @('health',   '2025', 'locked',  'DataStore.edb'),

    @('activity', '2019', 'clean',   'WebCacheV01.dat'),
    @('activity', '2019', 'crashed', 'WebCacheV01.dat'),
    @('activity', '2019', 'locked',  'WebCacheV01.dat'),

    @('resource', '2019', 'clean',   'SRUDB.dat'),
    @('resource', '2019', 'partial', 'SRUDB.dat'),
    @('resource', '2025', 'clean',   'SRUDB.dat'),
    @('resource', '2025', 'partial', 'SRUDB.dat'),

    # Client axis: synthetic Windows 11 24H2+ (build 26200 / 25H2) client,
    # generated by the exGOAD win11-ese extension. Both databases carry ESE
    # format revision 0x012C, identical to Windows Server 2025.
    @('health',   'w11-25h2', 'clean', 'DataStore.edb'),
    @('resource', 'w11-25h2', 'clean', 'SRUDB.dat')
)

$idx = 0
foreach ($s in $Samples) {
    $idx++
    $cat, $os, $state, $file = $s
    $dbPath = Join-Path $SamplesDir "$cat\$os\$state\$file"
    $stem = "$cat-$os-$state"

    Write-Host ("[{0,2}/19] {1}" -f $idx, $stem) -ForegroundColor Cyan

    if (-not (Test-Path $dbPath)) {
        Write-Warning "  Skipped: $dbPath not found"
        continue
    }

    # 1. esentutl /mh
    $esentutlOut = Join-Path $ValDir "$stem.esentutl.txt"
    & esentutl /mh "$dbPath" 2>&1 | Out-File -FilePath $esentutlOut -Encoding utf8
    Write-Host "      esentutl /mh -> $stem.esentutl.txt" -ForegroundColor Gray

    # 2. Poneglyph info
    $poneglyphOut = Join-Path $ValDir "$stem.poneglyph.txt"
    & "$Poneglyph" info --ntds "$dbPath" 2>&1 | Out-File -FilePath $poneglyphOut -Encoding utf8
    Write-Host "      poneglyph info -> $stem.poneglyph.txt" -ForegroundColor Gray

    # 3. Zeroed-page scan
    $zeroedOut = Join-Path $ValDir "$stem.zeroed.json"
    & "$ZeroScan" -Path "$dbPath" 2>&1 | Out-File -FilePath $zeroedOut -Encoding utf8
    Write-Host "      zeroed-page scan -> $stem.zeroed.json" -ForegroundColor Gray
}

# Replace old per-state files with the new naming scheme
Write-Host ""
Write-Host "Cleaning up legacy filenames..." -ForegroundColor Yellow
$legacy = Get-ChildItem -Path $ValDir -Filter 'poneglyph-info-*.txt' -ErrorAction SilentlyContinue
foreach ($f in $legacy) {
    Remove-Item -Path $f.FullName -Force
    Write-Host "  removed legacy: $($f.Name)" -ForegroundColor DarkGray
}

# Generate a summary index
$indexPath = Join-Path $ValDir 'INDEX.md'
$idxContent = @()
$idxContent += "# Validation outputs index"
$idxContent += ""
$idxContent += "Generated by `tools/run_full_validation.ps1` on $(Get-Date -Format 'yyyy-MM-dd')."
$idxContent += ""
$idxContent += "For each AAPF sample, this directory contains three verification artefacts:"
$idxContent += ""
$idxContent += "- `*.esentutl.txt` — Windows native ``esentutl /mh`` (page size, shutdown state, format revision)"
$idxContent += "- `*.poneglyph.txt` — Universal-patched ``libesedb`` parse output (tables, MSysObjects record counts)"
$idxContent += "- `*.zeroed.json` — Fully-zeroed page distribution (R4 evidence)"
$idxContent += ""
$idxContent += "| # | Category | OS | State | DB | esentutl | poneglyph | zeroed |"
$idxContent += "|---|---|---|---|---|---|---|---|"
$i = 0
foreach ($s in $Samples) {
    $i++
    $cat, $os, $state, $file = $s
    $stem = "$cat-$os-$state"
    $hasE = if (Test-Path (Join-Path $ValDir "$stem.esentutl.txt"))  { 'yes' } else { 'no' }
    $hasP = if (Test-Path (Join-Path $ValDir "$stem.poneglyph.txt")) { 'yes' } else { 'no' }
    $hasZ = if (Test-Path (Join-Path $ValDir "$stem.zeroed.json"))   { 'yes' } else { 'no' }
    $idxContent += "| $i | $cat | $os | $state | $file | $hasE | $hasP | $hasZ |"
}
$idxContent | Out-File -FilePath $indexPath -Encoding utf8

Write-Host ""
Write-Host "Done. INDEX.md written to $indexPath" -ForegroundColor Green

# Final report
$counts = @{
    esentutl  = (Get-ChildItem $ValDir -Filter '*.esentutl.txt'  -ErrorAction SilentlyContinue | Measure-Object).Count
    poneglyph = (Get-ChildItem $ValDir -Filter '*.poneglyph.txt' -ErrorAction SilentlyContinue | Measure-Object).Count
    zeroed    = (Get-ChildItem $ValDir -Filter '*.zeroed.json'   -ErrorAction SilentlyContinue | Measure-Object).Count
}
Write-Host ""
Write-Host "Outputs in ${ValDir}:" -ForegroundColor Cyan
Write-Host "  esentutl :  $($counts.esentutl) files"
Write-Host "  poneglyph:  $($counts.poneglyph) files"
Write-Host "  zeroed   :  $($counts.zeroed) files"
